FROM python:3.11-slim

WORKDIR /app

# Dipendenze Python
RUN pip install --no-cache-dir \
    faststream[kafka,cli] \
    pyais \
    requests

# Copia codice
COPY bridge_components.py /app/bridge_components.py
COPY config_loader.py /app/config_loader.py

# Avvio FastStream worker
CMD ["faststream", "run", "bridge_components:app"]